language: node_js
node_js:
- node
services:
- postgresql
addons:
  postgresql: '9.6'
dist: trusty
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "deployment-exercise-test";' -U postgres
before_deploy:
- rm -rf node_modules
deploy:
  skip_cleanup: true
  provider: heroku
  app: pair-exer-deploy-sol
  api_key:
    secure: Y7RbeQM5gHjuXSV9+gaYD2nPJxfzu1nr7h7UMwEaKWdkCBXQeoayVHaXs6BLTHHsUZ0Ga8YftbQkQnMZcO4+zyuU2mYvVTn/R5fj9hxkYiDU8+82JbDrH7OMbruUlVDXX4SNQx4yWZNTUE28XNfpc6ISz4VpyJiPa0Way9aAWPSqJJkmMzcz2Qro/asTpLRzN4TGQBuhLp29LcfbgUHgf3CcsAkPAkPf0gMrS4PmqRHgyJBL3nwbURtdkX1FyhBpD93GNAvk6gC451m3wOc+Dvag0ukp4bsZsxtMX6TaUp/cwl/K4h93oLfNOL+CswcEmAi5LX/owg9cGSsMtjM9CEZJFwtLxzzY8g0aCFu5MHYM4Tn0uPH8QBgOq6Latcs2thanr2B6dh+RvNi8nbp1n9jtCeYoIww5Nsg3oCOd334Ic9+U5MpW4oTCkoTpcgOi9lwhzKedL9QOLgBgzuyQ5dTXdl+E9CMCOi3dCQpYPWzxeZ0uSCh4y8s5YMSofO913uznDzP2W8+mTrFxOSQVvnK5OYVZdqTAaoDT2Mm/AhKQodXmP4osgYFG4MnYUgQxvySoAB4hBJTy2NULQf0PZYao9lKdU0CQXXjPkUeUIF9PchYKFKm88NTKSQzeOjcc9wXeA7Pk4Viuh8HasJG+9UWQK5sE3VE45U0cDjes9oU=
