language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  # - psql -c "CREATE USER nes WITH PASSWORD '2001fsnyc';" -U postgres
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: pair-exer-deploy-sol
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: qm0V3iWz5ZLZrV3eiTSOofZ8/wpyX2ccdjUph4w5zz8ufvlc3taFnFSyODADcYM4pm/64lPhANuQ6phE21vqO9K7gKFT7uaDJ9s+4S3K1fjIZFXkJBK+z6nHtxFm/cUzv7uzpTxx3wuTjFAJO2PnGd9nTt4plI34LaBDOIT6LVZjk0SscIm+qJ95uUkDvWiDzNizrRvOV46MisMRF7sGVw7AQptB49nMoTXejs/aeQ+KQN1L9IlPkZap3MIFjNCzX+MWg0LXFDfzv/+Ey42uWhztzGoQyHcLjEpWWAeDdjGEHA+VCw3ueXCQsa9w9GNocVM6zORGmH7ubhmtSqOVOnWlz+7biWhmDfz7n+4naE6ungjEGLTWudusaZkFcMuR2gDHSIQS/w0k+BNxEyPDoyxNBxw6fg+e9Q1zZOVB6RyNFZGHvWlk7zG30+UudMY9+eTM/9Je6SBCFSmBVbQwoloV8kIm8FQck+Wjmpt4FuBHOHc79oXbmh/oRHT/h7NX7QfwZ1vbCB4yXqegoqdeU7Lst0+QwfHq5qz8P31VLeqddcVQVVWUjE17+niGloIe/lDvXBl3FBIgmdG2NPlxtPfBDJAoYy2rEFpc5DnEakNVOAZRixnaYu4Qr0HPcegP7IoGXiKXywvuYl//03xF3x6e/9f0VWXqwQSLuuzT9U0=
